### ISSUE TITLE
How to start?

### ISSUE THREAD

**Issue by stewest** [girliemac/web-speech-ai#1]
Hi there

Love this! Trying it out. How do I start the node server? `npm start` nor `nf start` works.

**Comment by benrouba** [comment]
hi  do this node index.js

**Comment by stewest** [comment]
Hi thanks so much for getting back to me. Really dig this idea.

I still get this error, even when I have added the api tokens etc in the env file.
Locally should I be using the test env or just env? Thanks again

/git/iot/web-speech-ai/node_modules/apiai/module/apiai.js:73
        throw new Error('\'clientAccessToken\' cannot be empty.');
        ^

Error: 'clientAccessToken' cannot be empty.
    at createApplicationNew (/Users/stewwest/git/iot/web-speech-ai/node_modules/apiai/module/apiai.js:73:15)
    at createApplication (/Users/stewwest/git/iot/web-speech-ai/node_modules/apiai/module/apiai.js:96:37)
    at Object.<anonymous> (/Users/stewwest/git/iot/web-speech-ai/index.js:21:31)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)

**Comment by dilshad372** [comment]
Set  APIAI_TOKEN='xxxxxxxxxxxxxxxxxxx'  in env_test,   API Access token you will get from https://dialogflow.com/  when you click on setting for particular agent

**Comment by ask911** [comment]
even after setting the token im getting the same error mentioned above is there any reason for this

**Comment by nitinskumavat** [comment]
create .env file
And first run this line in cmd
"npm install dotenv --save"
this helped me

**Comment by leslysandra** [comment]
also, I just hardcoded my token at index.js
when declaring const apiai (it is for testing for myself!)

**Comment by venky1993** [comment]
How to use NPM start ? it shows below error while deploying 
 npm ERR! Failed at the test@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by nehabhat345** [comment]
I set the token as const APIAI_TOKEN='APxxxxxxxxxxxxx';
But it's showing the error as below:-
 Wrong response status code.
    at IncomingMessage.<anonymous> (D:\Projects_NEHA\web-speech-ai-master\web-speech-ai-master\node_modules\apiai\module\json_api_request.js:59:25)
    at IncomingMessage.emit (events.js:228:7)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  statusCode: 401,
  responseBody: '{\n' +
    '  "status": {\n' +
    '    "code": 401,\n' +
    '    "errorType": "unauthorized",\n' +
    '    "errorDetails": "Invalid access token: APxxxxxxxxxxxxx Code: 401"\n' +
    '  }\n' +
    '}',
  name: 'ServerError',
  message: 'Wrong response status code.'
}

**Comment by nehabhat345** [comment]
> also, I just hardcoded my token at index.js
> when declaring const apiai (it is for testing for myself!)

Did it work?
